### PR TITLE
29Bits support

### PR DESCRIPTION
**Pull request by Furtif**
- Fix https://github.com/cedricp/ecutweaker/issues/1

@cedricp look if good. Thanks!

### CODE REVIEW

**Comment by cedricp** [comment]
Looks right, but has it been tested ?

**Comment by Furtif** [comment]
> Looks right, but has it been tested ?

image
Download ZIP of source compile.

or uses git set this branch and pull and build

**Comment by Furtif** [comment]
Before merging, I prefer that @cedricp check if he can't build the code, you can use this compiled debug:
[EcuTweaker-debug.zip](https://github.com/cedricp/ecutweaker/files/13949107/EcuTweaker-debug.zip)
For ecu.zip read discussion https://github.com/cedricp/ddt4all/discussions/845

**Comment by Furtif** [comment]
## All TODO issues:
// TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/build.gradle#L27
// TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/ElmBase.java#L281
// TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/ElmBase.java#L310
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/ElmBase.java#L312
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/MainActivity.java#L439
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/MainActivity.java#L444
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/EcuTweaker/src/main/java/org/quark/dr/canapp/MainActivity.java#L449
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/ecu/src/main/java/org/quark/dr/ecu/ZipFileSystem.java#L100
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/CdcAcmSerialDriver.java#L289
//TODO; https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/CdcAcmSerialDriver.java#L355
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/CdcAcmSerialDriver.java#L360
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/CdcAcmSerialDriver.java#L365
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/CdcAcmSerialDriver.java#L381
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/Ch34xSerialDriver.java#L137
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/Ch34xSerialDriver.java#L303
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/FtdiSerialDriver.java#L186
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/FtdiSerialDriver.java#L237
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/FtdiSerialDriver.java#L427
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/FtdiSerialDriver.java#L453
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/driver/FtdiSerialDriver.java#L501
//TODO: https://github.com/cedricp/ecutweaker/blob/fix_29bits/usbserial/src/main/java/org/quark/dr/usbserial/util/SerialInputOutputManager.java#L123

**Pull request merged**
